### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by benschlup** [jacamo-lang/jacamo-lang.github.io#4]
Name: Framework for simulating task performance by Hybrid Intelligent Systems
Description (in one sentence): Extension for JaCaMo to support a generic task model with configurable tasks for human and computational agents to collaboratively work on.
Keywords: Hybrid Intelligence, Human-Machine Teaming, Task Environment
URLs: https://github.com/benschlup/hi_simulator

**Comment by jomifred** [comment]
thanks for the update. Your project was included in the JaCaMo web site!

**Comment by benschlup** [comment]
Hi Jomi,Thanks - I think below text went into the keyword column, that should be appended to the description and removed from Keywords?The part I am talking about:Extension for JaCaMo to support a generic task model with configurable tasks for human and computational agents to collaboratively work onThe keywords would be only:Hybrid Intelligence, Human-Machine Teaming, Task Environment.Kind regards, Ben Sent from my Galaxy
-------- Original message --------From: "Jomi F. Hubner" ***@***.***> Date: 6/12/24  18:06  (GMT+01:00) To: "jacamo-lang/jacamo-lang.github.io" ***@***.***> Cc: Ben Schlup ***@***.***>, Author ***@***.***> Subject: Re: [jacamo-lang/jacamo-lang.github.io] New Project (Issue #4) 
Closed #4 as completed.

**Comment by jomifred** [comment]
yes, you are right! I fault on C&P. I hope it is fixed now. thanks.
